theme = "Vesper"
padding-x = 0
padding-y = [0,0]
line-height = 1.3
confirm-before-quit = false

[renderer]
performance = "high"
backend = "automatic"
disable-unfocused-render = false
level = 1
filters = []


[fonts]
size = 16
family = "Liga SFMono Nerd Font"
features = []
use-drawable-chars = true
symbol-map = []
disable-warnings-not-found = false
additional-dirs = []


[fonts.regular]
family = "Liga SFMono Nerd Font"
style = "Normal"
width = "Normal"
weight = 400

[fonts.bold]
family = "Liga SFMono Nerd Font"
style = "Normal"
width = "Normal"
weight = 600

[fonts.italic]
family = "Liga SFMono Nerd Font"
style = "Italic"
width = "Normal"
weight = 400

[fonts.bold-italic]
family = "Liga SFMono Nerd Font"
style = "Italic"
width = "Normal"
weight = 600

[scroll]
multiplier = 4.0
divider = 1.0

[editor]
program = "helix"
args = []
