[colors]
background = '#100F0F'
foreground = '#CECDC3'
selection-background = '#CECDC3'
selection-foreground = '#403E3C'
cursor = '#CECDC3'
black = '#100F0F'
red = '#AF3029'
green = '#66800B'
yellow = '#AD8301'
blue = '#205EA6'
magenta = '#A02F6F'
cyan = '#24837B'
white = '#878580'
light_black = '#6F6E69'
light_red = '#D14D41'
light_green = '#879A39'
light_yellow = '#D0A215'
light_blue = '#4385BE'
light_magenta = '#CE5D97'
light_cyan = '#3AA99F'
light_white = '#CECDC3'
