[colors]
# Regular colors
background = '#101010'
black = '#101010'
blue = '#FFCFA8'
cyan = '#99FFE4'
foreground  = '#F9F4DA'
green = '#99FFE4'
magenta = '#A0A0A0'
red = '#FF8080'
white = '#ffffff'
yellow = '#FFCFA8'

# Cursor
cursor = '#FFCFA8'
vi-cursor = '#FFCFA8'

# Navigation
tabs = '#303030'
tabs-foreground = '#ffe6d8'
tabs-active = '#303030'
tabs-active-highlight = '#FFCFA8'
tabs-active-foreground = '#FFFFFF'
bar = '#303030'

# Search
search-match-background = '#FFCFA8'
search-match-foreground = '#101010'
search-focused-match-background = '#FFCFA8'
search-focused-match-foreground = '#101010'

# Selection`
selection-foreground = '#101010'
selection-background = '#303030'

# Dim colors
dim-black = '#101010'
dim-blue = '#99FFE4'
dim-cyan = '#99FFE4'
dim-foreground = '#FFC799'
dim-green = '#99FFE4'
dim-magenta = '#FFCFA8'


dim-red = '#FF8080'
dim-white = '#a0a0a0'
dim-yellow = '#FFC799'

# Light colors
light-black = '#232323'
light-blue = '#99FFE4'
light-cyan = '#99FFE4'
light-foreground = '#ffe6d8'
light-green = '#99FFE4'
light-magenta = '#FFC799'
light-red = '#FF8080'
light-white = '#a0a0a0'
light-yellow = '#ffe6d8'
