[colors]
background = '#101010'
foreground = '#ffffff'
selection-background = '#ffffff'
selection-foreground = '#101010'
cursor = '#ffffff'
black = '#101010'
red = '#f5a191'
green = '#90b99f'
yellow = '#e6b99d'
blue = '#aca1cf'
magenta = '#e29eca'
cyan = '#ea83a5'
white = '#a0a0a0'
light_black = '#7e7e7e'
light_red = '#ff8080'
light_green = '#99ffe4'
light_yellow = '#ffc799'
light_blue = '#b9aeda'
light_magenta = '#ecaad6'
light_cyan = '#f591b2'
light_white = '#ffffff'

