# Author : Tomas Ruud <git@me.2ms.no>

"ui.text" = "light-gray"
"ui.selection" = { fg = "white", bg = "gray" }
"ui.cursor" = { fg = "black", bg = "light-gray" }
"ui.cursor.primary" = { fg = "black", bg = "light-gray" }
"ui.cursor.match" = { modifiers = ["underlined"] }
"ui.background.separator" = "gray"
"ui.linenr" = "#393939"
"ui.linenr.selected" = { fg = "light-gray", bg = "#141414" }
"ui.statusline" = { bg = "#141414", fg = "#393939" }
"ui.menu" = { fg = "light-gray", bg = "#141414" }
"ui.menu.selected" = { bg = "light-gray", fg = "#141414" }
"ui.popup" = { fg = "light-gray", bg = "#141414" }
"ui.help" = { fg = "light-gray", bg = "#141414" }
"ui.virtual.ruler" = { underline = { style = "line"} }
"ui.cursorline.primary" = "#ffffff"

"string" = { bg = "light-green", fg = "#141414" }
"constant" = { bg = "light-cyan", fg = "#141414" }
"comment" = { bg = "light-magenta", fg = "#141414" }

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "gray"

"warning" = { fg = "light-yellow", bg = "#141414" }
"error" = { fg = "light-red", bg =  "#141414"}
"hint" = { fg = "light-blue", bg = "141414" }

"diagnostic.warning" = { fg = "black", bg = "light-yellow" }
"diagnostic.error" = { fg = "black", bg = "light-red" }
"diagnostic.hint" = { fg = "black", bg = "light-blue" }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }
